### ISSUE TITLE
Assignment03 peer reveiw

### ISSUE THREAD

**Issue by HJMcSorley** [STAT547-UBC-2019-20/group_13#18]
## Task 1
# Running scripts
- I cloned your project repo to my local
- I have all the indicated packages installed (and loaded into my library)
- To run your scripts, I copy and pasted the commands you indicated into in the repo README into my RStudio Terminal.
- None of the three scripts provided ran without error, so none of them generated the desired output 😞 

I think the issue is that in your scripts used ```read.csv(file = url)``` which (I beleive) only reads files from a local path. Try using ```download.file(url, output_path)``` to read the file from the online public repo and save it to an output location. _I made this same mistake._

Here were the errors I saw when I tried to execute the provided commands:
#### 'load_data.R' script command error:
```
Error:
  usage: src/load_data.R --url_to_read=<url_to_raw_data_file>
Execution halted
```

#### 'process_data.R' script command:
```
Error:
 usage: src/process_data.R --url_to_read=<url_to_raw_data_file>
Execution halted
```

#### EDA_script. R script command 
```
Error:
 usage: EDA_script.R --url_to_read=<url_to_clean_data_file>
Execution halted
```
  
 I think these were all due to way the url was read in ```read.csv()``` instead of ```download.file()```.

Here are some general comments from looking at the raw source code for your scripts:
* you did a nice job of using vectorized functions.
* I think you could call 'tidyverse' into the library and leave out loading 'dplyr', 'tidyr', and 'ggplot2' explicitly (because they're included in the tidyverse). Also, you called the 'glue' packaged into the library in 'load_data.R, but didn't use it.
* in the 'process_data.R' script, I think your function could have been streamlined into a pipe that filtered out any variable with NA values greater than 60% (for example), so that it could be executed without manually looking at the dataframe.

As none of the scripts ran properly based on the instructions posted, none of them generated any output. However, your README had a nice link to the knitted output from Milestone01 (on github pages) 

## Task 2
# EDA RMD feedback

Here are some general comments about the EDA, figures and language in the knitted git pages document.

:+1: Nice that you referenced the data sources and provided links, in case your reader wanted more information. 

:+1: You clarifyied what the variable 'HDI for year' was and why you decided to filter it out (70% NA values); that's good, it's helpful to know what was removed and why. 
 
### Plot comments  
__For the first plot (average number of suicides globally across generations):__
* you could either drop the legend (try ``` plot + theme(legend_position = "none")```) or suppress the column names, but it seems redundant to have the columns labeled and also show a legend.
* I think I would have liked to see the generations listed in order of the time period they occurred in (GI, silent, boomer, gen-x, millennial, gen-z). Because glancing at the plot as is (with ```fct_reorder(generation, mean_suicides)```) it looks like suicides have dropped off consistently.... but when you know the order that these groups came in, it's really interesting to see such a rise in suicides for the Baby-Boomer generation.  Maybe Gen-z has such low rates because they're the youngest generation alive at the moment (just a note).

__For the second plot (number of suicides in Canada):__
* This is pretty good and simple.
* Could have been interesting to do a ```facet_wrap()``` by sex (because your research question indicated that might be a focus)

__For the third plot (Distribution of suicides between sexes, globally):__
* I don't think the violin plot is very helpful because each group is so compressed (by an outlier in the 'males' category I think)... possibly filtering the outlier off of the plot, or maybe trying a density ridge plot would be more clear?

:+1: Your research questions was clear and interesting and your plan was simple and achievable. Good work!

**Comment by racquellem** [comment]
Hi @HJMcSorley, thanks for your very detailed and helpful feedback!

# Task 1: Running Scripts
- The TA, Matthew, commented how our scripts didn't run because of a space between  — and the argument. For example, we had:

`Rscript src/load_data.R -- url_to_read="https://raw.githubusercontent.com/STAT547-UBC-2019-20/data_sets/master/suiciderates.csv"`

When it should have been: 

`Rscript src/load_data.R --url_to_read="https://raw.githubusercontent.com/STAT547-UBC-2019-20/data_sets/master/suiciderates.csv"`

- I see how redundant it can be to load packages that are all already found in tidyverse! So will definitely simplify the loading of those ones. 

# Task 2: EDA Plots
- *First plot:* Yes, I think it would be a good idea to remove the legend. I was also thinking the same as well of putting the generations in order of the time period they appeared, as I even got confused sometimes with which one is older/younger than the other, age group etc. I will include factoring in low suicide rates b/c of Generation Z being the youngest when reaching conclusions, as I think this is a significant point to make!

- *Second plot:* Great idea! We were actually thinking of doing that for the first plot as well. 

- *Third plot:* We ended up doing a boxplot and log'd the y-axis, which I think ended up looking better than the violin. 

Cheers,
Racquelle
